In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 5, 3, 5, 1],
       [3, 9, 8, 8, 1],
       [8, 6, 6, 1, 9]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.24232978, 0.16682951, 0.42883529],
       [0.00234599, 0.68944177, 0.42147167],
       [0.63143927, 0.76970174, 0.12606427],
       [0.03445589, 0.26215679, 0.99212055],
       [0.19988762, 0.64981169, 0.27458364]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.12749242, 0.83075148, 0.25378774],
       [0.6305124 , 0.92062903, 0.79444319],
       [0.04170188, 0.56193036, 0.52831685],
       [0.44636746, 0.03582753, 0.54023986],
       [0.62110927, 0.36663994, 0.04255846]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [33]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [36]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.71932412, 0.41299183, 0.90642327],
       [0.18045162, 0.74111887, 0.42237404],
       [0.42645357, 0.63437987, 0.5229062 ],
       [0.41488598, 0.00142688, 0.09226235],
       [0.70939439, 0.5243456 , 0.69616046]])

In [37]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a1[0]

1

In [48]:
a2[0]

array([1. , 2. , 3.3])

In [47]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [52]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 5, 3, 0, 4],
         [8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5]],

        [[4, 4, 9, 9, 0],
         [6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6]],

        [[5, 9, 7, 5, 4],
         [9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9]]],


       [[[6, 2, 0, 5, 3],
         [0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9]],

        [[5, 1, 0, 0, 9],
         [1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7]],

        [[1, 0, 2, 7, 0],
         [0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4]]]])

In [53]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [54]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[4],
         [8],
         [3],
         [6]],

        [[4],
         [6],
         [4],
         [1]],

        [[5],
         [9],
         [5],
         [9]]],


       [[[6],
         [0],
         [4],
         [7]],

        [[5],
         [1],
         [0],
         [4]],

        [[1],
         [0],
         [5],
         [8]]]])

## 4. Manipulating & comparing arrays
### Arithmetic

In [55]:
a1

array([1, 2, 3])